# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import json
from PyQt6.QtWidgets import QApplication, QMainWindow, QLabel, QVBoxLayout, QHBoxLayout, QWidget, QScrollArea, QMessageBox
from customViews import Clickablewidget,Clickablelabel 
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import Qt
from test import GroceryApp
from functools import partial
from usermanager import UserManager
from PyQt6 import QtCore, QtGui, QtWidgets
from user import User
import argparse
from product import Products
 
import subprocess
from search import ProductSearch


currentwindow=None
All_products=[]

 # Load products from JSON file
file_path = 'products.json'
 








def show_products(products):
  
  

    # Load products from JSON file
    file_path = 'products.json'
    
    All_products=products
    
    # Create the app window and display products
    window = GroceryApp(products)
    print(len(products))
    window.setFixedHeight(600)
    window.setFixedWidth(850)
    window.show()
    #self.hide()
    sys.exit(app.exec())

    


class Ui_MainWindow(QMainWindow):
    


    def search(self,querry):
       search =ProductSearch("https://ecommerce-product-api1.p.rapidapi.com/data")
       search.search_products(querry)



    def vegetables_(self):
      products= self.search("Vegetables")
      print(products)
#       show_products(products)



    def canned_(self):
      products= self.search("canned foods")  
#       show_products(products)


       
    def protein_(self):
       products= self.search("protein")
#        show_products(products)
    


    def frozen_foods_(self):
      products= self.search("frozen foods")

    
    def dairy_(self):
     products=  self.search("frozen foods")
#      show_products(products)
    


    def baked_(self):
      products= self.search("baked")
#       show_products(products)

    def showscreen(self,app,user):
        
        # Create the app window and display products
        qw=QMainWindow()
        window = Ui_MainWindow(user)
        window.setFixedHeight(600)
        window.setFixedWidth(850)
        window.show()
        currentwindow=window
        
        sys.exit(app.exec())
        return currentwindow
    
 
    def showcart(self):
        email= self.user.email
        python_file = 'showcart.py'
       
         
        try:
           subprocess.run(['python', python_file, email], check=True)
        except subprocess.CalledProcessError as e:
           print(f"Error running {python_file}: {e}")
    def showuserdetails(self):
        email= self.user.email
        python_file = 'userview.py'
       
         
        try:
           subprocess.run(['python', python_file, email], check=True)
        except subprocess.CalledProcessError as e:
           print(f"Error running {python_file}: {e}")

    def on_enter_pressed(self):
       self.search(self.search_editor.text()) 


    def __init__(self, user):
        self.user=user
        super().__init__()
        self.MainWindow=QWidget()
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(784, 556)
        self.MainWindow.setStyleSheet("background:none; \n"
"background: rgba(255, 255, 255, 0.6)  url(./images/bg.png.png); \n"
" background-size: cover;\n"
" background-repeat: no-repeat;\n"
" ")
        
        
        self.centralwidget = QtWidgets.QWidget(parent=self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 250, 41))
        self.label.setStyleSheet("background:none;\n"
"font:  11pt \"Lucida Fax\";\n"
"color:rgba(0, 0, 0,.6)")
        
        self.setCentralWidget(self.MainWindow)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 60, 511, 491))
        self.widget.setStyleSheet("background:none;\n"
"background-color:#f6fafd;\n"
"border-radius:25px;\n"
"border-style:none;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(20, 20, 471, 151))
        self.widget_2.setStyleSheet("background:none;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0E74E8, stop:1 #174FC9);\n"
"border-radius:25px;\n"
"border-style:none;")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 221, 111))
        self.label_4.setStyleSheet("background-color:rgba(255, 255, 255,0);\n"
"font: italic 11pt \"Lucida Fax\";")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 181, 141))
        self.label_3.setStyleSheet("background:none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./images/lnd_img.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.vegetables = Clickablelabel(parent=self.widget)
        self.vegetables.setGeometry(QtCore.QRect(50, 230, 131, 101))
        self.vegetables.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #086FB1, stop:1 #03218F);\n"
"border-radius:25px;\n"
"border-style:none;")
        
        self.vegetables.clicked.connect(self.vegetables_)
        self.vegetables.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.vegetables.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.vegetables.setText("")
        self.vegetables.setPixmap(QtGui.QPixmap("./images/veg.jfif"))
        self.vegetables.setScaledContents(True)
        self.vegetables.setObjectName("vegetables")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 290, 131, 41))
        self.label_9.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"font-weight:bold;\n"
"background-color:rgba(0, 0, 0,.7);\n"
"border:none;\n"
"border-radius:0px;\n"
"")
        self.label_9.setObjectName("label_9")
        
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setGeometry(QtCore.QRect(60, 200, 121, 21))
        self.label_12.setStyleSheet("background:none;\n"
"font: 9pt \"Lucida Fax\";\n"
"color:rgba(0, 0, 0,.7)\n"
" ")
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setGeometry(QtCore.QRect(200, 290, 131, 41))
        self.label_10.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"font-weight:bold;\n"
"background-color:rgba(0, 0, 0,.7);\n"
"border:none;\n"
"border-radius:0px;\n"
"")
        self.label_10.setObjectName("label_10")
        self.dairy_products = Clickablelabel(parent=self.widget)
        self.dairy_products.clicked.connect(self.dairy_)
        self.dairy_products.setGeometry(QtCore.QRect(200, 230, 131, 101))
        self.dairy_products.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #086FB1, stop:1 #03218F);\n"
"border-radius:25px;\n"
"border-style:none;")
        self.dairy_products.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.dairy_products.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dairy_products.setText("")
        self.dairy_products.setPixmap(QtGui.QPixmap("./images/dd.jpg"))
        self.dairy_products.setScaledContents(True)
        self.dairy_products.setObjectName("dairy_products")
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setGeometry(QtCore.QRect(350, 290, 131, 41))
        self.label_11.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"font-weight:bold;\n"
"background-color:rgba(0, 0, 0,.7);\n"
"border:none;\n"
"border-radius:0px;\n"
"")
        self.label_11.setObjectName("label_11")
        self.frozen_foods = Clickablelabel (parent=self.widget)
        self.frozen_foods.clicked.connect(self.frozen_foods_)

        
        self.frozen_foods.setGeometry(QtCore.QRect(350, 230, 131, 101))
        self.frozen_foods.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #086FB1, stop:1 #03218F);\n"
"border-radius:25px;\n"
"border-style:none;")
        self.frozen_foods.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frozen_foods.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frozen_foods.setText("")
        self.frozen_foods.setPixmap(QtGui.QPixmap("./images/frozen.jfif"))
        self.frozen_foods.setScaledContents(True)
        self.frozen_foods.setObjectName("frozen_foods")
        self.label_13 = QtWidgets.QLabel(parent=self.widget)
        self.label_13.setGeometry(QtCore.QRect(50, 410, 131, 41))
        self.label_13.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"font-weight:bold;\n"
"background-color:rgba(0, 0, 0,.7);\n"
"border:none;\n"
"border-radius:0px;\n"
"")
        self.label_13.setObjectName("label_13")
        self.canned = Clickablelabel(parent=self.widget)
        self.canned.clicked.connect(self.canned_)
        self.canned.setGeometry(QtCore.QRect(50, 350, 131, 101))
        self.canned.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #086FB1, stop:1 #03218F);\n"
"border-radius:25px;\n"
"border-style:none;")
        self.canned.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.canned.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.canned.setText("")
        self.canned.setPixmap(QtGui.QPixmap("./images/canned.jfif"))
        self.canned.setScaledContents(True)
        self.canned.setObjectName("canned")
        self.label_15 = QtWidgets.QLabel(parent=self.widget)
        self.label_15.setGeometry(QtCore.QRect(200, 410, 131, 41))
        self.label_15.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"font-weight:bold;\n"
"background-color:rgba(0, 0, 0,.7);\n"
"border:none;\n"
"border-radius:0px;\n"
"")
        self.label_15.setObjectName("label_15")
        self.bakery = Clickablelabel(parent=self.widget)
        self.bakery.clicked.connect(self.baked_)
        self.bakery.setGeometry(QtCore.QRect(200, 350, 131, 101))
        self.bakery.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #086FB1, stop:1 #03218F);\n"
"border-radius:25px;\n"
"border-style:none;")
        self.bakery.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.bakery.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.bakery.setText("")
        self.bakery.setPixmap(QtGui.QPixmap("./images/bakery.jpg"))
        self.bakery.setScaledContents(True)
        self.bakery.setObjectName("bakery")
        self.label_17 = QtWidgets.QLabel(parent=self.widget)
        self.label_17.setGeometry(QtCore.QRect(350, 410, 131, 41))
        self.label_17.setStyleSheet("font: 9pt \"Segoe Print\";\n"
"font-weight:bold;\n"
"background-color:rgba(0, 0, 0,.7);\n"
"border:none;\n"
"border-radius:0px;\n"
"")
        self.label_17.setObjectName("label_17")
        self.protein = Clickablelabel(parent=self.widget)
        self.protein.clicked.connect(self.protein_)
        self.protein.setGeometry(QtCore.QRect(350, 350, 131, 101))
        self.protein.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #086FB1, stop:1 #03218F);\n"
"border-radius:25px;\n"
"border-style:none;")
        self.protein.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.protein.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.protein.setText("")
        self.protein.setPixmap(QtGui.QPixmap("./images/protein.jpg"))
        self.protein.setScaledContents(True)
        self.protein.setObjectName("protein")
        self.protein.raise_()
        self.label_17.raise_()
        self.bakery.raise_()
        self.label_15.raise_()
        self.canned.raise_()
        self.label_13.raise_()
        self.frozen_foods.raise_()
        self.label_11.raise_()
        self.dairy_products.raise_()
        self.label_10.raise_()
        self.widget_2.raise_()
        self.vegetables.raise_()
        self.label_9.raise_()
        self.label_12.raise_()
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.label_2.setStyleSheet("background:none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./images/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.user_icon =Clickablelabel(parent=self.centralwidget)
        self.user_icon.setGeometry(QtCore.QRect(740, 20, 31, 31))
        self.user_icon.setStyleSheet("background:none;")
        self.user_icon.setText("")
        self.user_icon.setPixmap(QtGui.QPixmap("./images/user_icon.png"))
        self.user_icon.clicked.connect(self.showuserdetails)
        


        self.user_icon.setScaledContents(True)
        self.user_icon.setObjectName("user_icon")
        self.cart_view = Clickablelabel(self.centralwidget)
        self.cart_view.setGeometry(QtCore.QRect(20, 480, 71, 51))
        self.cart_view.setParent(self.centralwidget)
        self.cart_view.setStyleSheet("background:none;")
        self.cart_view.setText("")
        self.cart_view.clicked.connect(self.showcart )

       
        self.cart_view.setPixmap(QtGui.QPixmap("./images/cart.png"))
        self.cart_view.setScaledContents(True)
        self.cart_view.setObjectName("cart_view")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(10, 80, 191, 31))
        self.widget_3.setStyleSheet("background:none;\n"
"background-color:#9BBAFF;\n"
"border-style:none;\n"
"border-radius:15px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.search_editor = QtWidgets.QLineEdit(parent=self.widget_3)
        self.search_editor.setGeometry(QtCore.QRect(20, 0, 141, 31))
        self.search_editor.setStyleSheet("color:#ffffff;")
        self.search_editor.setClearButtonEnabled(True)
        self.search_editor.setObjectName("search_editor")
        self.search_editor.returnPressed.connect(self.on_enter_pressed)
       
        self.statusbar = QtWidgets.QStatusBar(parent=self.MainWindow)
        self.statusbar.setObjectName("statusbar")
       

       

     
        _translate = QtCore.QCoreApplication.translate
       
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Hello, Welcome </span> 🖐️ "+ str(self.user.firstname)+"</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">Shop<br/>Anything<br/>Groceries</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:400; color:#ffffff;\">Vegetables</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">Categories</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:400; color:#ffffff;\">Dairy products</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:400; color:#ffffff;\">Frozen food</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:400; color:#ffffff;\">Canned goods</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:400; color:#ffffff;\">Bakery products</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:400; color:#ffffff;\">Protein foods</span></p></body></html>"))
        self.search_editor.setPlaceholderText(_translate("MainWindow", "Search..."))


if __name__ == "__main__":

 parser = argparse.ArgumentParser()
 parser.add_argument("argument", type=str, help="An argument to pass to the script.")
 args = parser.parse_args()

 print(args.argument)
 appp = QApplication(sys.argv)
 email=str(args.argument)
 UserMgr=UserManager()
 user= UserMgr.get_user_by_email(email)



 print(user.firstname)
 print(user.last_name)


 app=Ui_MainWindow(user)

 app.showscreen(appp,user)



